language: bash

env:
    global:
      - HUGO_VERSION=0.32.1
      - GIT_URL=https://git@github.com/gepuro/gepulog.git

notifications:
  slack:
    secure: "nJ5jcwb4yg+MRJFA0NklAwwMz5R+83/aUWA8oIQ8X3rPFdlQtGKwTWPR6tFW8HfvI/eSJnovTkFO6L7vdSIFh/wrgpQ5GOck3qBLD6vntHysbsQzhLNKSBZXzhkp0lFJrqhnHeYpXpKdSulMM2qH02MuPNk/ihvNb9TDYVTVA1ygrogactHuuIch79JjMuHwuh/JGIaqlBzTk/m1KbvqGcttk0z/LOjNdP4ILffnV1vGKV4eMSs6I/hjRJuU+2DhNQJ7djTBOnVlZtn/o/IP7tm7XPtyQY6j6vmYMRiPEbE6XJRA9IC4ffhZGmBVzbxGv6uKtHilRsmeH8yg88GtNjlJW7jthj8DmMisDh8Z4HX2SyP8K91rg2Cod+hzLtIG7oaN93Ftt51rY3Iu8pJ2Iz7lk8jo3ohL7xlVLWfOLvDFZunF9XgzSyOE3FMQbPkNweVVpDTKZYlCHyFgnp7HzgH/4dD0yRkSXd8EllMIHn77m/399Ka/F9SMP2PYuX4hyx/DNgkEWR+mj4Vma7IkO5iG9XspRXxt8D7FbysI/BKXrPDTAgyNDROZqZUOHpxWRjTIg3cdJZWAUEJhNRUVA7O2UAm5pH2YU9iL6bDT6qRJb5WJsRkY+1xy9X5SJRE6Qah8GycQ9w22GGhKABAhmAN69YbEbPFJ0Da8qaJktvw="

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar zxvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

after_success:
  - openssl aes-256-cbc -K $encrypted_6d24ef37b060_key -iv $encrypted_6d24ef37b060_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "example@example.com"
  - git config --global user.name "example user"
  - git clone git@github.com:example/example.git
  - cd example
  - cp -aR example_from_dir example_dist_dir
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push origin master

before_deploy:
  - mkdir docs
  - ./hugo -t kiss-master

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: blog.gepuro.net
  on:
    branch: master
