language: bash

env:
    global:
      - HUGO_VERSION=0.32.1
      - GIT_URL=https://git@github.com/gepuro/gepulog.git

notifications:
  slack:
    secure: "Q1FGKGSWn6evePLQg2NlxSMPN4pBlf+XEO0ur8PtPSFip2RFT6mwQeyjLuZj8OBUqkPiZqhrC6HmdlgnYzouE3z819WW81YokC+v5nqo9T9PMeSS6Yfh8+k7I/HMjmmUqGkxtsMXwYEEoo7wf2Y3293o8guVatlk8mDE67UTriCXuAWWwZjOnTk6G9fwKXR5iqJgyvcETdBYZlXcS/MDRca/WhINFoLtbi/F6fytMDeXFM71ckCJKB5N9Z8if1GN2XIU1sL17ELD1HgDd6iCx44OV344G+4sSqJV8AGtLQDbvTLe5UNw67AfF4dAZ3ys3/4a9vFCk4kWFWFm8h8eekrAz6IJk4WuToGVkD09ObNtO7OGMO9U6RcGzv8DGpDzY6ifXune5ooyLVkzeSLSo/TOiFADP0rbwus8X1G5uBuEyHuS1I+rJgfyZ1hKLkSbwB55L4LD14Dplzp51z2GaeI7twY3MCk0F/fAuqFK0hroF52xTOD6RhbimUMe/iJ7p/JgQD/g2Dwf4RPE8aPx6c5t6f7/oVHUPXfLelEcjSHe91rINTHt6t6p9gHyW3UyrCip9THhT4TU73RoC+u8J8QLqrEWDOkOqT2ch1XoJ4/isEJUXEglSTsiVNKZMdSSLNL03i2VvxzUQw24UurFEBhv0oiBCW5NyrcHKgPUCfk="

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar zxvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

after_success:
  - openssl aes-256-cbc -K $encrypted_6d24ef37b060_key -iv $encrypted_6d24ef37b060_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "example@example.com"
  - git config --global user.name "example user"
  - git clone git@github.com:example/example.git
  - cd example
  - cp -aR example_from_dir example_dist_dir
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push origin master

before_deploy:
  - mkdir docs
  - ./hugo -t kiss-master

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: blog.gepuro.net
  on:
    branch: master
